language: python
python:
  - '3.9'
  - '3.6'
before_install:
  - python --version
  - pip install --upgrade pip setuptools==44.0.0
install:
  - make install-dev # install package + test dependencies
script: 
  - make tests # run tests
#https://towardsdatascience.com/extensive-python-testing-on-travis-ci-4c24db9bf961